name: Terraform Validate

on:
  push:
    branches: [main]
    paths:
      - 'iac/**'
  pull_request:
    paths:
      - 'iac/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [before, after]
    steps:
      - uses: actions/checkout@v6

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: '~1.6'

      - name: Terraform Format Check
        run: terraform fmt --check -recursive
        working-directory: iac/environments/${{ matrix.environment }}

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: iac/environments/${{ matrix.environment }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: iac/environments/${{ matrix.environment }}
