name: tfsec

on:
  pull_request:
    paths:
      - 'iac/**'

jobs:
  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: iac
